# Generated by Django 2.1.1 on 2018-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='map',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
    ]
