# Generated by Django 2.1.1 on 2018-09-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=True, related_name='my_profile', to='user.User'),
        ),
    ]
